#   
#    ####             ####
#   ######           ######         i3status
#    ####             ####          config file
#
#   ########################        gryzlee
#    ######################
#     ###################           Note: This config outputs any status element
#       ################       
#

general {
        colors = true
        interval = 1
}

order += "tztime local"