#!/usr/bin/env sh

# ------------------------------------------------------------------------------
# Apps                                                                         |
# ------------------------------------------------------------------------------

# xdg-open is similar to open on macOS
alias o='xdg-open'
alias open='xdg-open'

# $EDITOR must be set
alias e='$EDITOR'

# Use all available cores for make.
alias make='make --jobs=$(nproc)'
alias m='make'

alias py='python'

# A vim-like TUI file explorer
alias ra='ranger'

# Tmux is a terminal multiplexer
alias t='tmux'
alias ta='tmux attach'

# ------------------------------------------------------------------------------
# Administration                                                               |
# ------------------------------------------------------------------------------

# https://wiki.archlinux.org/title/Sudo#Passing_aliases
#
# Preserve user environment. The extra space allows the next commands to
# be aliases too
alias sudo='sudo --preserve-env '

# Edit with sudo privileges while keeping the editor user config
alias sudoe="sudoedit"

# ------------------------------------------------------------------------------
# Everything else                                                              |
# ------------------------------------------------------------------------------

alias c='clear'
alias cl='clear'
alias clr='clear'
alias cls='clear'

alias cd..='cd ..'
alias ..='cd ..'

alias q='exit'
alias quit='exit'
alias :q='exit'
alias :wq='exit'

alias h='history'

alias ls='ls --human-readable --classify --group-directories-first --color=auto'
alias l='ls'
alias la='ls --almost-all'
alias ll='ls -l --almost-all'

# Ask before nuking
alias cp='cp --recursive --interactive --verbose'
alias mv='mv --interactive --verbose'
alias rm='rm --dir --recursive --interactive=once --verbose'

alias mkdir='mkdir --parents --verbose'
alias rmdir='rmdir --parents --verbose'

alias ln='ln --interactive --verbose'
alias lns='ln --symbolic'

alias chmod='chmod --preserve-root --changes'
alias mod='chmod'

alias chown='chown  --preserve-root --changes'
alias own='chown'

alias chgrp='chgrp --preserve-root --changes'
alias grp='chgrp'

alias du='du --human-readable --total'

# Exclude system filesystems
alias df='df --human-readable --total -x tmpfs -x devtmpfs -x efivarfs'

alias free='free --human --total'

# Show changes together
alias diff='diff --recursive --unified --color=auto'

alias f='find'

alias grep='grep --color=auto'
alias egrep='grep --extended-regexp'

alias less='less -R --use-color'

alias ip='ip --human-readable --color=auto'
