#!/bin/sh

# ------------------------------------------------------------------------------
# Apps                                                                         |
# ------------------------------------------------------------------------------

# xdg-open is similar to open on macOS
alias o='xdg-open'
alias open='xdg-open'

# $EDITOR must be set
alias e="$EDITOR"

# Use all available cores for make.
alias make='make --jobs=$(nproc)'
alias m='make'

alias py='python'

alias s='ssh'

# A vim-like TUI file explorer
alias ra='ranger'

# ------------------------------------------------------------------------------
# Administration                                                               |
# ------------------------------------------------------------------------------

# https://wiki.archlinux.org/title/Sudo#Passing_aliases
#
# Preserve user environment. The extra space allows the next commands to
# be aliases too
alias sudo='sudo --preserve-env '

# Edit with sudo privileges while keeping the editor user config
alias sudoe="sudoedit"

# ------------------------------------------------------------------------------
# Git                                                                          |
# ------------------------------------------------------------------------------

alias g='git'
alias ga='git add --all'
alias gc='git commit --all --message'
alias gb='git checkout'
alias gp='git push'
alias gpp='git pull'

# ------------------------------------------------------------------------------
# Package managers                                                             |
# ------------------------------------------------------------------------------
# p: install
# prm: remove
# pq: query all explicitly installed local packages
# pqi: query info about a package
# pqs: query installed package by name
# pss: search in repositories by name
# pcl: clean up non required packages
# pcc: clean up cache

if command -v yay >/dev/null; then
	alias p='yay -Syu'
	alias prm='yay -Rs'
	alias pq='yay -Qe'
	alias pqi="yay -Qi"
	alias pqs='yay -Qss'
	alias pss='yay -Ss'
	alias pcl='yay -Rs $(yay -Qdtq)'
	alias pcc='yay -Scc'
elif command -v pacman >/dev/null; then
	alias p='sudo pacman -Syu'
	alias prm='sudo pacman -Rs'
	alias pq='pacman -Qe'
	alias pqi='pacman -Qi'
	alias pqs='pacman -Qss'
	alias pss='pacman -Ss'
	alias pcl='sudo pacman -Rs $(pacman -Qdtq)'
	alias pcc='sudo pacman -Scc'
fi

# ------------------------------------------------------------------------------
# Everything else                                                              |
# ------------------------------------------------------------------------------

alias c='clear'
alias cl='clear'
alias clr='clear'
alias cls='clear'

alias cd..='cd ..'
alias ..='cd ..'

alias q='exit'
alias quit='exit'
alias :q='exit'
alias :wq='exit'

alias h='history'

alias ls='ls --human-readable --classify --group-directories-first --color=auto'
alias l='ls'
alias la='ls --almost-all'
alias ll='ls -l --almost-all'

# Ask before nuking
alias cp='cp --recursive --interactive --verbose'
alias mv='mv --interactive --verbose'
alias rm='rm --dir --recursive --interactive=once --verbose'

alias mkdir='mkdir --parents --verbose'
alias rmdir='rmdir --parents --verbose'

alias ln='ln --interactive --verbose'
alias lns='ln --symbolic'

alias chmod='chmod --preserve-root --changes'
alias mod='chmod'

alias chown='chown  --preserve-root --changes'
alias own='chown'

alias chgrp='chgrp --preserve-root --changes'
alias grp='chgrp'

alias du='du --human-readable --total'

# Exclude system filesystems
alias df='df --human-readable --total -x tmpfs -x devtmpfs -x efivarfs'

alias free='free --human --total'

# Show changes together
alias diff='diff --recursive --unified --color=auto'

alias f='find'

alias grep='grep --color=auto'
alias egrep='grep --extended-regexp'

alias less='less -R'

alias ip='ip --human-readable --color=auto'

# Colorized man pages
man() {
	# mb -> Blink
	# md -> Bold
	# so -> Standout (line bar and search match)
	# us -> Underline
	env \
		LESS_TERMCAP_mb=$(printf '\033[1;38;5;229m') \
		LESS_TERMCAP_md=$(printf '\033[1;38;5;216m') \
		LESS_TERMCAP_so=$(printf '\033[1;38;5;3m') \
		LESS_TERMCAP_us=$(printf '\033[4;1;38;5;222m') \
		LESS_TERMCAP_me=$(printf '\033[0m') \
		LESS_TERMCAP_se=$(printf '\033[0m') \
		LESS_TERMCAP_ue=$(printf '\033[0m') \
		GROFF_NO_SGR=1 \
		man "$@"
}
