#!/usr/bin/env sh

if [[ ! -f "/etc/arch-release" ]]; then
  return
fi


if command -v yay >/dev/null; then
  # p: install
  alias p='yay -Syu'
  # prm: remove
  alias prm='yay -Rs'
  # pq: query all explicitly installed local packages
  alias pq='yay -Qe'
  # pqi: query info about a package
  alias pqi="yay -Qi"
  # pqs: query installed package by name
  alias pqs='yay -Qss'
  # pss: search in repositories by name
  alias pss='yay -Ss'
  # pcl: clean up non required packages
  alias pcl='yay -Rs $(yay -Qdtq)'
  # pcc: clean up cache
  alias pcc='yay -Scc'
elif command -v pacman >/dev/null; then
  alias p='sudo pacman -Syu'
  alias prm='sudo pacman -Rs'
  alias pq='pacman -Qe'
  alias pqi='pacman -Qi'
  alias pqs='pacman -Qss'
  alias pss='pacman -Ss'
  alias pcl='sudo pacman -Rs $(pacman -Qdtq)'
  alias pcc='sudo pacman -Scc'
fi
