#!/usr/bin/env sh

if [ ! -f "/etc/debian_version" ]; then
	return
fi

# p: install
p() {
	sudo apt update
	sudo apt upgrade --yes
	[ $# -ne 0 ] && sudo apt install "$@"
}

# prm: remove
alias prm='sudo apt remove --autoremove'

# pq: query all explicitly installed local packages
alias pq='apt-mark showmanual'

# pqi: query info about a package
alias pqi='apt show'

# pqs: query installed package by name
alias pqs='apt list --installed | grep '

# pss: search in repositories by name
alias pss='apt search'

# pcl: clean up non required packages
alias pcl='sudo apt autoremove'

# pcc: clean up cache
alias pcc='sudo apt clean'
