#!/usr/bin/env sh

check_suse() {
    if [ -f /etc/os-release ]; then
        echo "$(cat /etc/os-release | grep '^NAME' | cut -d '=' -f 2 | tr -d '"')" | grep -qi "suse" && return 0
    fi

    return 1
}

check_suse || return

# p: install
p() {
    # Enable parallel downloads and use modern media backend
    local ZYPP_PCK_PRELOAD=1 ZYPP_CURL2=1
    sudo zypper update --no-confirm
    [ $# -ne 0 ] && sudo zypper install "$@"
}

# prm: remove
alias prm='sudo zypper remove'

# pq: query all explicitly installed local packages
alias pq='zypper search --installed-only | grep -v i+'

# pqi: query info about a package
alias pqi='zypper info'

# pqs: query installed package by name
alias pqs='zypper search --installed-only'

# pss: search in repositories by name
alias pss='zypper search'

# pcl: clean up non required packages
alias pcl='echo "Zypper does not have an easy way to do this, :("'

# pcc: clean up cache
alias pcc='sudo zypper clean --all'
