#!/usr/bin/env sh

check_suse() {
    if [ -f /etc/os-release ]; then
        cat /etc/os-release | grep '^NAME' | cut -d '=' -f 2 | tr -d '"' | grep -qi "suse" && return 0
    fi

    return 1
}

check_suse || return

# p: install
p() {
    # Enable parallel downloads and use modern media backend
    local ZYPP_PCK_PRELOAD=1 ZYPP_CURL2=1
    sudo zypper dist-upgrade --no-confirm --no-recommends
    [ $# -ne 0 ] && sudo zypper install "$@"
}

# prm: remove
alias prm='sudo zypper remove --clean-deps'

# pq: query all explicitly installed local packages
alias pq="zypper search --installed-only | grep -v '^i\+ '"

# pqi: query info about a package
alias pqi='zypper info'

# pqs: query installed package by name
alias pqs='zypper search --installed-only'

# pss: search in repositories by name
alias pss='zypper search'

# pcl: clean up non required packages
pcl() {
    sudo zypper rm --clean-deps "$(zypper packages --unneeded | tail -n +5 | cut -d ' ' -f 8)"
}

# pcc: clean up cache
alias pcc='sudo zypper clean --all'

unset -f check_suse
