[window]
dynamic_padding = true
opacity = 0.8

[scrolling]
history = 100000

[font]
normal = { family = "Hack Nerd Font" }
size = 12

[colors]
transparent_background_colors = true

[cursor]
style = { blinking = "On" }
unfocused_hollow = false

[mouse]
hide_when_typing = true
