# Polybar

[colors]
background = #282a36
background-alt = #273248
foreground = #FFFFFF

[bar/main]
width = 100%
height = 24pt
radius = 0
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = "JetBrainsMono Nerd Font:pixelsize=16; 3"

padding-left = 1
padding-right = 1
module-margin = 1
separator = |

fixed-center = true

modules-left = window
modules-center = workspaces
modules-right = battery date

tray-position = right 

enable-ipc = true

#override-redirect = true
#wm-restack = i3

include-file = window.ini
include-file = workspaces.ini
include-file = battery.ini
include-file = date.ini
