# Polybar

[colors]
bg = #B21F2430
focus = #8775B0
foreground = #FFFFFF

[bar/bottom]
width = 100%
height = 20pt
radius = 0
bottom = true

background = ${colors.bg}
foreground = ${colors.fg}

font-0 = "FiraCode Nerd Font:pixlesize=10; 3"

padding-left = 1
padding-right = 1
module-margin = 1
separator = |

fixed-center = true

modules-center = workspaces
modules-left = audio battery backlight keyboard
modules-right = network date

tray-position = right 

enable-ipc = true

[bar/top]
width = 100%
height = 24pt
radius = 0
bottom = false 

background = ${colors.bg}
foreground = ${colors.fg}

font-0 = "NotoSans Nerd Font:pixelsize=16; 3"

padding-left = 1
padding-right = 1
module-margin = 1
separator = |

fixed-center = true

modules-left = files memory
modules-right = network keyboard audio backlight battery date

enable-ipc = true

#override-redirect = true
#wm-restack = i3

include-file = window.ini
include-file = workspaces.ini
include-file = battery.ini
include-file = date.ini
include-file = audio.ini
include-file = backlight.ini
include-file = files.ini
include-file = memory.ini
include-file = network.ini
include-file = keyboard.ini
