#
# ~/.config/tmux/tmux.conf
#

#------------------------------------------------------------------------------
# Keybinds
# ------------------------------------------------------------------------------

# prefix: <ctrl-Space>
unbind    C-Space
set -g    prefix C-Space
bind      C-Space send-prefix

# Unbind some useless commands
unbind w        # Window preview
unbind t        # Show clock

# Use hjkl to navigate panes
bind -N "Move left"     h   select-pane -L
bind -N "Move down"     j   select-pane -D
bind -N "Move up"       k   select-pane -U
bind -N "Move right"    l   select-pane -R

# Resize with Alt for bigger step, Ctrl for smaller step
bind -r -N "Resize the pane left by 5"   M-h   resize-pane -L 5
bind -r -N "Resize the pane down by 5"   M-j   resize-pane -D 5
bind -r -N "Resize the pane up by 5"     M-k   resize-pane -U 5
bind -r -N "Resize the pane right by 5"  M-l   resize-pane -R 5
bind -r -N "Resize the pane left"        C-h   resize-pane -L 1
bind -r -N "Resize the pane down"        C-j   resize-pane -D 1
bind -r -N "Resize the pane up"          C-k   resize-pane -U 1
bind -r -N "Resize the pane right"       C-l   resize-pane -R 1

# Split horizontally/vertically. Bound to mimic Vim behaviour
bind -N "Split horizontally"  v   split-window -h
bind -N "Split vertically"    s   split-window -v

# <prefix> m to sync panes
bind -N "Synchronize panes"   m   setw synchronize-panes

# <prefix> b to break a pane to a new window
bind -N "Break pane to new window"  b   break-pane

# Layout shortcuts
bind -N "Select tiled layout"             +   select-layout tiled
bind -N "Select even horizontal layout"   ç   select-layout even-vertical

# A more convenient way to enter copy mode
bind -N "Enter copy mode"   y   copy-mode

# ------------------------------------------------------------------------------
# Commands
# ------------------------------------------------------------------------------

# Kill session quickly
set -g command-alias[100] kys=kill-session

# Reload config file
set -g command-alias[101] reload="source-file ~/.config/tmux/tmux.conf"

# ------------------------------------------------------------------------------
# Config
# ------------------------------------------------------------------------------

# Enable mouse support (Shift to escape)
set -g mouse on

# Start indexing with 1
set -g base-index 1
setw -g pane-base-index 1

# Actually enable clipboard
set-option -g set-clipboard on

# Renumber windows if one in the middle is closed
set -g renumber-windows on

# ------------------------------------------------------------------------------
# Visual
# ------------------------------------------------------------------------------

# Hacky solution for 256-color and proper font rendering
set -g default-terminal "${TERM}"
set -a terminal-overrides ',xterm-256color:RGB'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Disable bell
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Status bar format
set -g status-position bottom
set -g status-justify left
set -g status-left ''
set -g status-right ' #S '
setw -g window-status-current-format ' #I: #W #F '
setw -g window-status-format ' #I #W #F '

# Status bar colors
setw -g mode-style "fg=#ebdbb2 bg=#d79921 bold"
set -g pane-border-style "fg=#32302f"
set -g pane-active-border-style "fg=#fabd2f"
set -g status-style "fg=#ebdbb2 bg=#32302f"
set -g status-right-style "fg=#1d2021 bg=#b16286"
setw -g window-status-current-style "fg=#1d2021 bg=#458588"
setw -g window-status-style "fg=#ebdbb2 bg=#32302f"
setw -g window-status-bell-style "fg=#fabd2f bg=#32302f bold"
set -g message-style "fg=#ebdbb2 bg=#32302f bold"

# vim: ft=tmux ts=2 sts=2 sw=2 et:
