#!/bin/bash
# Common aliases for bash

# Color ls output
alias ls='ls --color=auto'

# Symlinks all files in the .dotfiles directory 
alias restow='pushd $HOME/.dotfiles &> /dev/null && stow --restow --target=$HOME */ && popd &> /dev/null'

# quit also exits 
alias quit='exit'

# Script for quick access to config files
dotconf () {
    local CONFIG_PATH=$HOME/.config
    
    [ $# -eq 0 ] && echo "dotconfig: No arguments" && return 1
    [ $# -ne 1 ] && echo "dotconfig: Only one argument at a time" && return 1

    case $1 in
        alacritty|i3|polybar)
            $EDITOR $CONFIG_PATH/$1
        ;;
        bash)
            $EDITOR $BASH_CONFIG_PATH
        ;;
        bashrc)
            $EDITOR $HOME/.bashrc 
        ;;
        *) 
            echo "dotconfig: Invalid argument" && return 1
        ;;
    esac

    return 0
}
