#!/bin/bash
# Common aliases for bash

# Color ls output
alias ls='ls --color=auto'

# Resource .bashrc
alias reload='source $HOME/.bashrc'
# quit also exits 
alias quit='exit'

# Quick access to ssh hosts
sshx() {
    ssh -X a817570@$@.cps.unizar.es
}

# Access relevant dotfiles quickly
cfg () {
    local CONFIG_PATH=$HOME/.config
    
    [ $# -eq 0 ] && echo "cfg: No arguments" && return 1
    [ $# -ne 1 ] && echo "cfg: Only one argument at a time" && return 1

    case $1 in
        alacritty|i3|picom|polybar)
            $EDITOR $CONFIG_PATH/$1
        ;;
        bash)
            $EDITOR $BASH_CONFIG_PATH
        ;;
        bashrc)
            $EDITOR $HOME/.bashrc 
        ;;
        *) 
            echo ": Invalid argument" && return 1
        ;;
    esac

    return 0
}

# Commit changes in dotfiles and restow
dot() {
    if pushd $HOME/.dotfiles &> /dev/null
    then
	    git add *
	    git commit -m "$(date '+%Y/%m/%d %H:%M') $@"
        stow --restow --target=$HOME */
	    popd &> /dev/null
    fi
}

# Generate document from markdown file with pandoc
mdgen() {
    for f in $@; do
        pandoc $f.md \
	-f markdown \
	--pdf-engine=xelatex \
        --highlight-style kate \
        -V geometry:a4paper \
        -V geometry:margin=2cm \
        -V documentclass=report \
        -V lang=es-ES \
        --toc \
        --top-level-division=chapter \
        -N \
        -o "$f.pdf"
    done
}
