#!/bin/bash
# Globbing and autocompletion options

# If command is name of directory, cd into it
shopt -s autocd

# Autocorrect minor typos when using cd
shopt -s cdspell

# Include files starting with . when globbing (excl. '.' and '..')
#shopt -s dotglob

# Extended globbing
shopt -s extglob

# Case-insensitive globbing
shopt -s nocaseglob

# Don't show autocompletion for empty prompt
shopt -s no_empty_cmd_completion

# If alias exists, tries autocompletion for command
shopt -s progcomp_alias
