#!/bin/bash
# Prompt shown in terminal

# Returns asterisk when uncommited files are present
function get_git_dirty {
    [[ $(git status --porcelain 2> /dev/null) ]] && echo "*"
}

# Returns git branch name
function get_git_branch {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/ (\1 $(get_git_dirty))/"
}

COLOR_BLUE1="\[$(tput setaf 39)\]"
COLOR_BLUE2="\[$(tput setaf 45)\]"
COLOR_BLUE3="\[$(tput setaf 51)\]"
COLOR_GREEN="\[$(tput setaf 192)\]"
COLOR_YELLOW="\[$(tput setaf 226)\]"
COLOR_RESET="\[$(tput sgr0)\]"

export PS1="$COLOR_BLUE1\u$COLOR_BLUE2@$COLOR_BLUE3\h $COLOR_GREEN\w$COLOR_YELLOW\$(get_git_branch)$COLOR_RESET $ "